### ISSUE TITLE
Nostalgy++ settings locks up Thunderbird

### ISSUE THREAD

**Issue by dmusican** [opto/nostalgy-xpi#139]
This seems to be new... clicking on the wrench icon in the add-on, or alternatively going to Tools, Nostalgy++.... completely locks Thunderbird up. Tried disabling all other add-ons, no help. Using TB 78.14.0, Nostalgy++ 3.0.11. Any thoughts?

**Comment by mdonz** [comment]
I noticed the following behaviour here (TB 91.3.2, 64 bit on Ubuntu 20.04, Nostalgy++ 3.0.8):
Running the system monitor at the time that I try to open Nostalgy's settings, the memory usage for TB will start increasing from the usual (about 400MB) up to almost 5GB (laptop has 16GB RAM) and then finally will actually open the Nostalgy Preference. Once the preference window is active and usable, memory usage has dropped back about 400MB

**Comment by sphh** [comment]
I also experienced a frozen Thunderbird. After a restart I opened the error console, which does not spit out any messages (it gets frozen too). So I started TB from the terminal to capture the error messages. Here we go:

TB: 78.14.0 (64-bit)
Mail manage/Nostalgy++: 3.0.8
Linux Mint 20.2
```
[…]
JavaScript error: undefined, line 0: Error: Missing host permission for the tab
JavaScript error: undefined, line 0: Error: Missing host permission for the tab
console.log: "in onNostalgyEditPrefsLoad"
```

I did not wait as long as @mdonz, but killed Thunderbird.

I then updated the add-on to 3.0.11. Now I can open the preferences dialog without error message. I can also add a new rule by pressing `New` from the `Rules` tab. What I must not do is to switch from the new rule window back to the main Thunderbird window and select a mail message. Then TB locks up and uses a lot of RAM (for me the memory consumption goes up to 4.5GB out of available 8GB, then the laptop freezes and the memory consumption of TB drops back to the usual amount just to start increasing again. This goes on and on until I kill TB.) The terminal shows the error message:
```
JavaScript error: undefined, line 0: Error: Missing host permission for the tab
```

If I press `Shift-N` to add a new rule straight from a message, TB ‘locks’ itself immediately.

**Comment by sphh** [comment]
I also found another way to lock Thunderbird and nostalgy++ 3.0.11 (I do not know, if this is related, but the symptoms are the same, so I added it to this issue, but please feel free to suggest to open a new issue):
If I select a message, for which no rule exists, TB becomes unresponsive, uses more and more memory, laptop freezes, memory is freed, TB uses more and more memory, …

If I downgrade to 3.0.8, I can select the message again without any problem.

**Comment by opto** [comment]
I tested the idea with ressource monitor on Win 11, but no freeze or increase of RAM.
1) do you have a lot of rules?
2) or very small RAM?

Klaus

**Comment by sphh** [comment]
>     1. do you have a lot of rules?
I cannot test, because I cannot open the preference windows … But from memory I have between 5 or 7 rules.

>     2. or very small RAM?
I run my Linux System on a box with 8GB of RAM. I tried this with only Thunderbird running as the only user started program – same effect.

> Then TB locks up and uses a lot of RAM (for me the memory consumption goes up to 4.5GB out of available 8GB, then the laptop freezes and the memory consumption of TB drops back to the usual amount just to start increasing again. This goes on and on until I kill TB.)

The 4.5GB RAM mentioned in my https://github.com/opto/nostalgy-xpi/issues/139#issuecomment-981797996 refers to the free RAM, which is completely used up.

**Comment by mdonz** [comment]
> I noticed the following behaviour here (TB 91.3.2, 64 bit on Ubuntu 20.04, Nostalgy++ 3.0.8):
Running the system monitor at the time that I try to open Nostalgy's settings, the memory usage for TB will start increasing...
By now I am running TB 91.4.0 (still Ubuntu 20.04 with Nostalgy++ 3.0.8) and the issue is still happening, when trying to go into the Nostalgy++ settings, TB starts allocating more and more memory.
I have then installed Nostalgy++ 3.0.11 again (over the top of 3.0.8, hope that's OK) and the issues are initially the same (memory increase) but actually they seem worse - after a fresh start of TB, without opening the Nostalgy++ settings and only using a Nostalgy ++ key (quick filter), the key seems not to be working and the system monitor shows the memory usage to increase rapidly again. 
I seem not to have much luck with version 3.0.11 and reverted back to 3.0.8 for now.

**Comment by sphh** [comment]
@mdonz: Are you sure that the behaviour you experience for `3.0.11` isn't that one described in #134? Same result (eating all available memory), but possibly different causes …

**Comment by opto** [comment]
please try 3.1.3 https://github.com/opto/nostalgy-xpi/releases/tag/v3.1.3

**Comment by opto** [comment]
please try 3.1.3 https://github.com/opto/nostalgy-xpi/releases/tag/v3.1.3

swich off the ption for conversation /thread search if necessary

**Comment by sphh** [comment]
:clap: The preference window opens instantly and I can change all settings. Thanks!!

If it were up to me, this issue could be closed.

**Comment by mdonz** [comment]
> @mdonz: Are you sure that the behaviour you experience for 3.0.11 isn't that one described in #134? Same result (eating all available memory), but possibly different causes …
Sorry, did not check #134 before but I can report that the installation of version 3.1.3 (so far) seems to make all the difference! No more memory abuses and all Nostalgy++ functionality that I am using seems to work (no rules in use) so right now I am happy and see this as the fix that I was waiting (hoping) for. Thanks @opto for all your work on this important Thunderbird extension

**Comment by opto** [comment]
thanks
