### ISSUE TITLE
Keys don't work after returning from email if not if first tab

### ISSUE THREAD

**Issue by Izwbusr** [opto/nostalgy-xpi#170]
Hi,

Using 91.6.2 (64-bit), Windows 10, Nostalgy 3.2.17.

This happens only for tabs that are not the first.  So, if you have more than one inbox or if you have other folders open in tabs, you may have this problem.

If you select a message and click a key to perform an action, then it works normally.  But, if you open the message and close it, then the keys do not work.  You have to select another tab and then return to the tab you were working on for keys to "reset" and work again.

I love Nostalgy (donated for development), but it is getting too buggy for too long,

**Comment by opto** [comment]
buggy ... to respell it ... the continous TB conversion to a webapplication is killing off features that always worked out of the box

**Comment by opto** [comment]
I can confirm this for Win 11. The problem is in versions since TB ca. 78, that we don't have windows for the mail:3pane (therewas an extra overlay for them), but that we now have to inject all code into the top part of the window. That also holds calendar and other stuff where our letters need to be inactive.

So now we have to detect that we are in a mail window, and send the info there there so that it reactivates the keys. If there are several mail:3pane tabs, that seems to be somewhat unreliable.

does it help to change this option: restrict commands to email tab? But then, Nostalgy eats your keys everywhere (e.g. in event descriptions, as I was told). But aybe you don't need them.

Klaus

**Comment by Izwbusr** [comment]
With version 91.8.0 and Nostalgy 3.2.17 I can confirm that keys do not work if returning focus to anything other than the first email tab.  Cycling to first email tab and back to other email tabs, fixes the problem.

I think this is related to your last message

**Comment by opto** [comment]
new version with new startup and tab handling (by TB team member):  https://github.com/opto/nostalgy-xpi/releases/tag/v3.3.19

**Comment by Izwbusr** [comment]
I can confirm that with versions 91.8.0 and Nostalgy 3.3.19 the problem persists.  When returning focus (from another application) to any tab other than the first email tab, keys do not work.  Cycling to first email tab and back, fixes the problem.

**Comment by herrminni** [comment]
I can also confirm, that the problem is still there with v3.3.19 and Thunderbird 91.7.0 running in Ubuntu 21.10.

Exactly the same behavior as Izwbusr reported:
When returning the focus from another app to Thunderbird, the Nostalgy shortcuts are not working.
Switching to the first tab and back to another tab makes shortcuts work again.

Thunderbird system shortcuts (like "F" for the next message) on the other hand, do not have this problem when the app gets focus again and not on the first tab.

**Comment by opto** [comment]
please try 3.3.21 under releases

**Comment by herrminni** [comment]
Hi @opto,
I just installed it in Thunderbird 91.7.0 running in Ubuntu 21.10 and I can not reproduce the problem any more.
Very nice! :-) Thank you very much for taking the time to fix this issue!

**Comment by Izwbusr** [comment]
Thank you.  This is fixed for me as well.
