### ISSUE TITLE
1.0.16 now go/save/copy not working at all

### ISSUE THREAD

**Issue by PointInSpace2** [opto/nostalgy-xpi#19]
With the new version 1.0.16 go/save/copy are now not working at all.  In the message list, the nostalgy field at the bottom is permanently there.  But no function to move messages, either in the message list or message detail window when pulled up.

**Comment by dmusican** [comment]
Agreed, I'm in the same place. With 1.0.16, nothing none of the keyboard shortcuts work at all (they were working in the last release).

**Comment by rogerval** [comment]
Me too, I'm afraid.
Neither shortcut s or g works (haven't tried any other features at this stage).
Ubuntu Mate 19.10
Nostalgy 1.0.16
(But thanks to the developers for all this; Nostalgy is one of my "must have" addons. :-) )

**Comment by opto** [comment]
which OS? tested on Win 10 home. I went through all shortcuts to test them before release.

**Comment by dmusican** [comment]
Ubuntu 18.04; Thunderbird 68.2.2.

(and yes, thank you so much for working on this!)

**Comment by opto** [comment]
please try 1.0.16a

**Comment by salzrat** [comment]
I can report that keys are working on latest Thunderbird (69) under Windows 7 with 1.0.16a.

I did have the xpi from the main page here installed, but I think it's an older one. But I now upgraded to 1.0.16a and it still works.

Comment: it's confusing to have different xpis around!

**Comment by PointInSpace2** [comment]
Works great now!  *Thanks* for all of your work on this, you're a lifesaver!

**Comment by dmusican** [comment]
1.0.16a works great. Many thanks!

**Comment by CaptEpsilon** [comment]
1.0.16a is now working for me Win10 Home. Thanks for the updates!

**Comment by rogerval** [comment]
Sorry to be the fly in the ointment, but...
On TB 68.2.2 under Ubuntu Mate 19.10 and with Nostalgy 1.0.16a I'm still having issues.
Pressing s toggles the star on that message, rather than activating Nostalgy "move message".
Pressing c brings up a "mark messages as read by date" dialog, rather than activating Nostalgy "copy message".
Pressing g or G does nothing.
(I should add that I've used previous versions of Nostalgy under Windows 7 with great success.)
Perhaps this is an issue with Ubuntu Mate 19.10 (but I note that dmusican apparently has had success with Ubuntu 18.04, and of course I'm happy for him. :-) )
I'd temporarily edit the Thunderbird keyboard shortcuts, but the two addons Mozilla themselves suggest to achieve this, are themselves unable to work with TB 68, and at least 1 author hasn't the time (understandably) to play catch-up with the Thunderbird developers. <sigh>
(Thunderbird support article here: https://support.mozilla.org/en-US/kb/keyboard-shortcuts#w_customize-or-disable-keyboard-shortcuts )
Once again, thanks for your hard work, it's greatly appreciated. :-)
Roger V.
