### ISSUE TITLE
Nostalgy++ 3.6.x branch: input box stays open in status bar after first usage

### ISSUE THREAD

**Issue by trulycool** [opto/nostalgy-xpi#191]
Just upgraded Nostalgy++ to 3.5.2 for TB 102 compatibility. The Nostalgy++ text input box that has always popped up when engaging shortcut key, shown destination, then disappeared after filing email, now stays expanded (tho blank) after first usage.

Any way to revert to previous behavior? Or failing that, could you post the CSS class I'd add to userchrome to style to box to be less glaringly white in TB dark theme?

**Comment by opto** [comment]
maybe try this version: https://github.com/opto/nostalgy-xpi/releases/tag/v3.6.5

... it does not do that here on 102.3.1

**Comment by trulycool** [comment]
Thank you, have just installed 3.6.5 and still seeing the same behavior. Anything else I might do to help troubleshoot this?
![image](https://user-images.githubusercontent.com/821458/195190171-a0cedcf2-b187-447d-b9ee-94c4bc054e6b.png)

**Comment by opto** [comment]
is it open (you can type in it) or maybe it is hidden or collapsed, but TB does not change the color?

**Comment by ungeahnt** [comment]
In the grey box you can see the "[+Shift]"-hint (written in white letters). This is definitely not the input box. The area simply does not change color in the dark theme. So it only looks like the inputbox. Despite this color-problem you can use nostalgy++ quite normal.
I'm actually using the light theme, but I switched to the dark theme for testing and I can reproduce the color issue. Whether this is a TB or nostalgy++ issue I can't say though.

**Comment by opto** [comment]
thanks. So I need to verify whether we apply any CSS to that area - then it is Nostalgy - or not, which would hint to TB.

The same happens here, but it is very snall, like 5 mm. There is this vertical bar at the end, which looks like a splitter.
What is the number of characters for your input box? it is 70 here, see options.

**Comment by opto** [comment]
maybe a TB issue?

How much experience do you have with debugger tools?

You can open the tools by ctrl-shift-i, all at the same time. Then you need to allow debugging to be opened in a TB popup (might be hidden behind the main window).
click on the inspector tab and then on the icon to its left. Mouse hover says something like choose element on the page

next switch to TB using the task bar. Moving the mouse across the screen shows blue areas, put that onto the annoying white area. If you click and go back to inspector, you see the definition of that element.
If you just move the mouse and don't click,  you see the ids and classes of the element.
Here, the white thing is a hbox with class statusbar and our label with class statusbarpanel. Both belong to TB, and the unread count is also a statusparpanel and is displayed correct.

So this seems to be TB related? Because we don't inject any CSS for those two.

**Comment by opto** [comment]
outdated
