### ISSUE TITLE
Sometimes I become trapped inside the Search box

### ISSUE THREAD

**Issue by TigBuh99** [opto/nostalgy-xpi#192]
Occasionally I find that no matter what keystroke I use, everything is entered in the Search box and I simply cannot get out of it using the keyboard. The only solution is to use my mouse in order to clear the accumulated keystrokes in the Search box.

**Comment by TigBuh99** [comment]
Multiple ESC doesn't help, but it simply adds it in the search box. As @salzrat wrote above.

**Comment by Olifair** [comment]
I can confirm, too. Same thing here. But I haven't figured out yet under what conditions one gets "trapped". I will try to keep my eyes open.

**Comment by internationils** [comment]
I've had the same thing when moving a mail to a folder (and then not wanting to), with ESC or DEL showing up. Had to click elsewhere on the bottom status bar to get out

**Comment by internationils** [comment]
TB102.4.0 N3.6.1

**Comment by ungeahnt** [comment]
issue can be reproduced (Win8.1, TB102.4.0 (64-Bit)):

1. use shortcut "s" or "g", so that search box becomes active
2. click with the mouse to another e-mail or folder in Thunderbird
3. after this the cursor is 'trapped' and ESC-key no longer works as expected and it writes only 'Escape' in the search box). 
4. any click on the status bar is necessary to end this 

In practice, the problem occurs when I enter a search term that doesn't exist (between step 1. and 2.) and I do not explicitly quit the search with ESC (e.g. because I click directly on another e-mail or on a folder in the directory tree).

I think the search box should be closed when a mouse click appears outside the search box / result list.

**Comment by TigBuh99** [comment]
> issue can be reproduced (Win8.1, TB102.4.0 (64-Bit)):
> 
> 1. use shortcut "s" or "g", so that search box becomes active
> 2. click with the mouse to another e-mail or folder in Thunderbird
> 3. after this the cursor is 'trapped' and ESC-key no longer works as expected and it writes only 'Escape' in the search box).
> 4. any click on the status bar is necessary to end this
> 
> In practice, the problem occurs when I enter a search term that doesn't exist (between step 1. and 2.) and I do not explicitly quit the search with ESC (e.g. because I click directly on another e-mail or on a folder in the directory tree).
> 
> I think the search box should be closed when a mouse click appears outside the search box / result list.

I can confirm the above also on Windows 11 v.22H2 TB 102.4.1 (64 bit)

**Comment by szmontsaroff** [comment]
I can confirm for Windows 10 as well.

**Comment by doegox** [comment]
It occurs also under Linux.
TH102.4.2
Nostalgy++ 3.6.1

**Comment by opto** [comment]
the bad things is that we test for this already: if (ev.key == "Escape") but it seems it does no longer work (it did when I introduced that a long time ago)

**Comment by opto** [comment]
this follows ungeahnt's proposal to close box on blur for input box: https://github.com/opto/nostalgy-xpi/releases/tag/v3.6.12

**Comment by doegox** [comment]
Thanks! It fixes the issue for me

**Comment by TigBuh99** [comment]
Based on a quick test I can conclude that it's fixed for me too.

**Comment by tonycanike** [comment]
Thank you!  Fixed it for me, this was a distracting problem, glad it's resolved.

**Comment by opto** [comment]
resolved
