### ISSUE TITLE
Arrow keys on Windows 10

### ISSUE THREAD

**Issue by ziomau10** [opto/nostalgy-xpi#24]
Dear all,
thank you for the good job.
Nostalgy is very useful to me.
I am on Windows 10 (1909) and recently upgraded to TB 86.3.1.
I installed nostalgy from Opto version 1.021.

I am finding that when I press s, a list of recent folders appears, but:
The list is not the latest, but looks like the previous one (i.e. the last used entry is not there).
Then, pressing the up arrow key, instead of scrolling through the list nothing happens.

I can confirm that typing a search word, immediately updates the list to the matching folders, and at that point the up and down arrows work again.

I can also confirm that the trick, I read about here, to press the left arrow followed by the up arrow restore the correct history list, and then allows to scroll it up and down.

Is this the intended behavior?
Or is it a problem with my installation?
I am under the impression tha the original nostalgy (with TB < 68) didn't work this way.

Thanks for any help.
Regards.
Mau.

**Comment by opto** [comment]
hello,

the history didn't even work on TB 60. There is some undiscovered change in TB sourcecode and functioning. I tried to debug but didn't find what changed in TB before TB 60.

So at the moment, the workaround is needed.

**Comment by Olifair** [comment]
Hello, 
I have the same problem, using "statistical prediction" option (in the completion tab). This actually worked in TB60 (both, the prediction and the arrow key). Now it seems that the predictions works, but not the arrow key. Left arrow and up does work, but only shows history, not the prediction. 
But otherwise I'm really happy that you had ported this to TB 68, thanks very much

**Comment by opto** [comment]
this works in 78, but see #29 until I have updated
