### ISSUE TITLE
Different (latest) Versions V4.1.14 - V4.2.15 - V4.3.16

### ISSUE THREAD

**Issue by ungeahnt** [opto/nostalgy-xpi#275]
Github shows as latest release: **V4.1.14**

[Thunderbird Extensions](https://addons.thunderbird.net/en-US/thunderbird/addon/nostalgy_ng/versions/) shows also **V4.2.15 - V4.3.16:**

Should I use V4.3.16 for Thunderbird 128.3.1esr?

![grafik](https://github.com/user-attachments/assets/5069c2c9-d0cb-4343-9e20-4632b5a5ed6b)

**Comment by Olifair** [comment]
I'm using 4.3.16 with  Thunderbird 128.3.1esr and it works just fine, well, at least what I use : S,G,B, the shifts and the prediction :-)

**Comment by ungeahnt** [comment]
Thanks for the reply. I've now installed 4.3.16 and I'll test it.

But why there is a newer version on the Extension page and whats the differences between 4.1.14 and 4.3.16? I can't find any information about 4.3.16 beside that it was released 7th of October.

**Comment by WBTMagnum** [comment]
v4.2.15 did not work properly with TB 115 (see #273). Opto fixed this with 4.3.16.

Why there is no release on Github I cannot tell. I couldn't find any release notes either.

**Comment by ungeahnt** [comment]
Thanks. I will close due its not a real issue

**Comment by r2evans** [comment]
My _inference_: opto needed to make sure all users of TB-115 with auto-update enabled to update to the non-128 version, the only way to do that was to make the version number greater than the 4.2.15 he had released for TB-128. Perhaps the 4.2 of 4.2.15 was a mistake or an intention for "big update" as it settles down (chasing TB's web-extension api).

I suspect when opto has more time and as they are more comfortable with the state of the two TB-115 and TB-128 versions, they may choose to do a version-number change. Or perhaps 4.2 --> TB-128 and 4.3 --> TB-115, and we already have that change ... though I'm not certain that 4.3.16 is the desired version for TB-128.

This 115/128 debacle is a headache ...

**Comment by ungeahnt** [comment]
Yes, the add-in strategy of the Thunderbird developers is extremely difficult to understand. I hope they have already realised that the add-in concept needs to be much more forward-looking to create a more stable interface over the time.

**Comment by r2evans** [comment]
> hope they have already realised

I like your optimism @ungeahnt but do not share it. IIRC, every generation of Thunderbird has broken some if not "a lot" of the backward compatibility for plugins. In some markets it might make sense<sup>1</sup>, but I find it to be somewhat incompatible with the open-source "free as in speech" mindset that Mozilla generally espouses. While I have no assumption that it is intentional, it does seem casually ignorant if not negligent.

<sup>1. I'm looking at Microsoft, the SMB protocol, and several other components where they have had little incentive to encourage/support non-Microsoft solutions, though MS is certainly not the only one nor the worst</sup>
