### ISSUE TITLE
TAB expansion doesn't work on new rule dialog

### ISSUE THREAD

**Issue by maherma-adg** [opto/nostalgy-xpi#36]
On creating/editing a rule, when you type on source and target folder fields, Nostalgy show suggested folders but TAB keyboard doesn't expand selected one as it does on copy/move message field.

**Comment by opto** [comment]
I think I noticed that as well. A momentary workaround is to delete the typed characters

**Comment by opto** [comment]
this truely was tricky and really time consuming. In theory, a little thing. In praxis, the handling of keydown in edit rules is not handled in edit rules- where it would be expected - , but in a totally different place. So adding the right handling for keydown and tab leads to wonderment, because nothing happens ....
anyway, we got it: tab cycles through the proposals. Enter accepts. Another tab jumps to the next input field. Final tab goes to ok button

**Comment by opto** [comment]
https://github.com/opto/nostalgy-xpi/releases

Nostalgy++ 2.2.3 with new features

@opto opto released this now

This release has some new features:

    Esc-r shows/opens the attachment list of a message. Esc-1 (-2, -3 etc.) displays the first, second ... image attachment. No longer do we need to open an external image viewer to have a preview of Photo/image attachments.

    The width of the folderbox in characters can be set in a pref.

    The help text in statusbar has been put into a tooltip to give more space for long foldernames.
