### ISSUE TITLE
Usual status bar text appears left instead of right-hand side

### ISSUE THREAD

**Issue by ferencr** [opto/nostalgy-xpi#5]
Standard status bar text like "Unread: 0    Total: 3   Today Pane" appears left instead of right-hand side. (See picture. Win 10 HUN, TB 68.2.2 64bit HUN)

P.S.: Thanks a lot for your work!!!

![2019-11-20 172447](https://user-images.githubusercontent.com/12916135/69257060-b3684880-0bba-11ea-833f-4a17a39f3001.png)

**Comment by konmax** [comment]
Just found the same issue which might appear as a minor thing but a very negative side effect is that the left area of the status bar is also used to display URLs when hover over a link from a mail with the mouse. Such links are not visible anymore which is a major problem because this is an important security functionality when it comes to spam mails.

Other than that, the latest version performs great and I'm really thankful for the TB 68 port!

Konrad

**Comment by opto** [comment]
didn't notice that yet. That is indeed more than cosmetic

**Comment by konmax** [comment]
Hi,

That's what I thought, too. Would be cool if you could fix this issue.
Other than that, everything works great ;-)

Are you thinking about making this an official TB add-on? At least for
me and my workflow it is crucial and I really love it!

Thanks
Konrad

Am 28.11.2019 um 09:23 schrieb opto:

**Comment by rmmbr** [comment]
>  didn't notice that yet. That is indeed more than cosmetic

@opto 
No, it's not only cosmetic. I agree with konmax. When putting the mouse over a Link, you can't see the real adress in the statusbar. Whithout nostalgy the link is visible in the statusbar. Under security aspects this should by corrected.

**Comment by opto** [comment]
solved, will upload today

**Comment by konmax** [comment]
This is good news! Did you already upload it? Somehow I still see the
old version online...

Thanks
Konrad

Am 18.12.2019 um 17:32 schrieb opto:
