### ISSUE TITLE
hotkeys interfering with calendar

### ISSUE THREAD

**Issue by lynnebsyd** [opto/nostalgy-xpi#81]
It seems that N++ is activating while in the calendar tab on Thunderbird. e.g. if I try to create a new event with the first letter being "s", it moves the focus to the N++  "Move messages to: "entry box at the bottom of the screen.

It would be good for it to be inactive in the calendar tab.

Thanks!

**Comment by opto** [comment]
which version of TB, N++ and OS?

I have set calendar to create events in a tab, and there, if focus in event name, all is as expected. Or what did you do precisely?

I noticed that an S in calendar overview opens the folder input box. That is due to the fact that mailextensions could not detect calendar tabs until a few versions ago (nly other tabs). I think that TB bug is solved by now, if yes, I will correct this behaviour.

Klaus.

**Comment by opto** [comment]
solved in 2.2.6 (not uploaded yet)

**Comment by lynnebsyd** [comment]
Fantastic! Thank you so much.

Lynne

**Comment by opto** [comment]
v2.3 will be uploaded soon.
